project:
  type: website
  output-dir: docs
website:
  title: "A Journey Within"
  
  navbar:
    left:
      - href: index.qmd
        text: About Me
      - href: papers.qmd
        text: Papers
      - href: workshops.qmd
        text: Workshops
      - href: blog.qmd
        text: Blog
      
  sidebar:
    style: "docked"
    logo: "./images/myu.png"
    search: true
    collapse-level: 2
    contents:
      - icon: github
        text: Github
        url: https://github.com/amruthaajish17
      - icon: instagram
        text: Instagram
        url: https://www.instagram.com/i._.am_ruthaaa/
      - icon: Email
      - text: "Email"
        url: mailto:amruthaajishachuthan@gmail.com
      
  announcement: 
    icon: info-circle
    dismissable: true
    content: "**Alert** - This Website is created using `Quarto` and Published as Github Pages"
    type: primary
    position: below-navbar
format:
  html:
    theme: quartz
    css: styles.css
    toc: true
  


